apiVersion: v1
kind: Service
metadata:
  name: {{ include "catchpoint-backend-dev.fullname" . }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
